#pragma once

#include <CriBase.h>

enum CriError
{
    CRIERR_OK = 0x0,
    CRIERR_NG = 0xFFFFFFFF,
    CRIERR_INVALID_PARAMETER = 0xFFFFFFFE,
    CRIERR_FAILED_TO_ALLOCATE_MEMORY = 0xFFFFFFFD,
    CRIERR_UNSAFE_FUNCTION_CALL = 0xFFFFFFFC,
    CRIERR_FUNCTION_NOT_IMPLEMENTED = 0xFFFFFFFB,
    CRIERR_LIBRARY_NOT_INITIALIZED = 0xFFFFFFFA,
    CRIERR_ENUM_BE_SINT32 = 0x7FFFFFFF
};